name: Software_Development
description: Revanth Pothukuchi And Amal Jacob's Project For TSA's Software Development.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  
  firebase_core: ^0.4.0
  firebase_analytics: ^1.0.4

  cloud_firestore: 0.13.4

  firebase_auth: ^0.15.2
  google_sign_in: ^4.1.0

  shared_preferences: 0.5.6+2

  url_launcher: 5.4.2

  geolocator: ^5.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: JosefinSans
      fonts:
        - asset: fonts/JosefinSans-Regular.ttf
        - asset: fonts/JosefinSans-SemiBold.ttf
          weight: 400
        - asset: fonts/JosefinSans-Bold.ttf
          weight: 700
