name: software_development
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  
  firebase_core: ^0.2.5
  firebase_analytics: ^1.0.4

  cloud_firestore: 0.8.2+3

  firebase_auth: 0.6.6
  google_sign_in: ^3.2.4

  rxdart: 0.20.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true


  fonts:
    - family: JosefinSans
      fonts:
        - asset: fonts/JosefinSans-Regular.ttf
        - asset: fonts/JosefinSans-SemiBold.ttf
          weight: 400
        - asset: fonts/JosefinSans-Bold.ttf
          weight: 700
